### ISSUE TITLE
renderAfterDocumentEvent for every page

### ISSUE THREAD

**Issue by afontcu** [Tribex/prerenderer#1]
Hi! Is there a way to "hold" *every* page before the Event is dispatched instead of waiting for the event and then prerender all the pages?

I need to wait for my API response in every page so I'm dispatching an event when the data has been passed to my component, but only the first page gets its content properly rendered.

I'm using the [webpack plugin](https://github.com/Tribex/prerenderer-webpack-plugin) with Vue and axios.

Thanks in advance!

**Comment by Tribex** [comment]
@afontcu Hmm, that should be the default behavior, I think you may have discovered a bug. Which renderer are you using? (JSDOM, Chrome, or Browser?)
Thanks for pointing this out!

**Comment by afontcu** [comment]
Currently BrowserRenderer. I'll give Chrome a go, just in case.

Maybe I'm just doing something wrong and there's no bug 😇  it's my first time trying to prerender an SPA.


my config (pretty straightforward):

```js
    new PrerendererWebpackPlugin({
      staticDir: path.resolve(__dirname, '../dist'),
      routes: [ '/', 'categories/some-permalink' ],
      renderer: new BrowserRenderer({
        renderAfterDocumentEvent: 'api-ready'
      })
    })
```

**Comment by Tribex** [comment]
@afontcu That looks right!
I find it odd that such a bug would occur in BrowserRenderer or ChromeRenderer given that the event processing for those is entirely separate.

Digging through things...

**Comment by Tribex** [comment]
@afontcu Hmm, I can't seem to reproduce this with `BrowserRenderer`. As far as I can tell it's working fine. I tried with a page that fetches from an API with a random offset of around 10 - 60 seconds and each page finished when the request completed.

My best guesses would be:
1. It looks like you're using a relative path in `routes`. I should probably clarify in the documentation that all paths specified in `routes` should be absolute.
In your case, that would look like:

```javascript
routes: [ '/', '/categories/some-permalink' ],
```

2. (I'm guessing this might be the issue.) When setting reactive data with Vue, you should wait to send the document event until after Vue re-renders the component. ie, don't send the event until `vm.$nextTick`.

Don't do this:
```javascript
axios.get(MyAPIURL)
.then(res => res.json())
.then(data => {
  this.data = data
  document.dispatchEvent(new Event('api-ready'))
})
```

Instead, do this:
```javascript
axios.get(MyAPIURL)
.then(res => res.json())
.then(data => {
  this.data = data

  this.$nextTick(() => {
    document.dispatchEvent(new Event('api-ready'))
  })
})
```

I'll try and clarify those issues in the documentation soon so that they don't trip people up.

If neither of those help with your problem, it would be great if you could send a more complete set of files so we can more easily diagnose the issue.

**Comment by afontcu** [comment]
Hi again,

I tried to move the event dispatcher to component's `mounted()` hook and everything worked as expected. I guess using the `$nextTick())` trick would do it aswell, gonna try it as soon as I get home.

Thanks for your time!


ps: my bad, I'm using absolute paths 💃 just a typo.

**Comment by Tribex** [comment]
Awesome, glad that fixed it! Enjoy!
